version : '3'

services:
    php:
      build: .
      depends_on:
            - mysql
      volumes: 
            - ./:/var/www/html
            - /var/log/apache2/app:/var/log/apache2/
      ports:
            - 8080:80
    mysql:
      image: mysql:8.0  # Uses the official MySQL image
      ports:
        - "3306:3306"  # Maps port 3306 on the host to port 3306 in the container
      environment:
        MYSQL_ROOT_PASSWORD: root  # Root password for MySQL
        MYSQL_DATABASE: ewo  # Initial database to create
      volumes:
        - mysql-data:/var/lib/mysql  # Persists MySQL data in a named volume

volumes:
  mysql-data:  # Declares a named volume for MySQL data persistence